language: c

matrix:
  include:
  - os: osx
    compiler: clang

arch:
  - x86_64

before_install:
# Travis branch-specific clone problem workaround:
- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch

before_script: 
- git clone https://github.com/edithturn/42-libft-functions.git libft
- pwd
- ls
script: bash run_test_t.sh
