# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yannahbrutout <yannahbrutout@student.42    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/17 13:58:34 by yannahbruto       #+#    #+#              #
#    Updated: 2022/01/17 14:03:21 by yannahbruto      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = GlobalBanksters_united

CC = clang++

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

SRC =	Account.cpp \
		test.cpp\

all:
	$(CC) $(CPPFLAGS) $(SRC) -o $(NAME)
clean:
	@rm -f phone_book